// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD85KKXAwIJhPMMnaLVdEjhVIpaiWPk6gw',
    appId: '1:21321383900:web:0854422440bce43aa75919',
    messagingSenderId: '21321383900',
    projectId: 'go-router-practice',
    authDomain: 'go-router-practice.firebaseapp.com',
    storageBucket: 'go-router-practice.firebasestorage.app',
    measurementId: 'G-M8MFKYBNRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXC1TwG7J1JXTQLs4AQtjx_dztCkuf_k',
    appId: '1:21321383900:android:fa48c8f1a9c38986a75919',
    messagingSenderId: '21321383900',
    projectId: 'go-router-practice',
    storageBucket: 'go-router-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTOVrIPgnsnN0_W7u6CNHhRtxJXOUuoxI',
    appId: '1:21321383900:ios:ca6ef5a7b7f258b7a75919',
    messagingSenderId: '21321383900',
    projectId: 'go-router-practice',
    storageBucket: 'go-router-practice.firebasestorage.app',
    iosBundleId: 'com.example.goRouterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTOVrIPgnsnN0_W7u6CNHhRtxJXOUuoxI',
    appId: '1:21321383900:ios:ca6ef5a7b7f258b7a75919',
    messagingSenderId: '21321383900',
    projectId: 'go-router-practice',
    storageBucket: 'go-router-practice.firebasestorage.app',
    iosBundleId: 'com.example.goRouterPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85KKXAwIJhPMMnaLVdEjhVIpaiWPk6gw',
    appId: '1:21321383900:web:690de242c941a026a75919',
    messagingSenderId: '21321383900',
    projectId: 'go-router-practice',
    authDomain: 'go-router-practice.firebaseapp.com',
    storageBucket: 'go-router-practice.firebasestorage.app',
    measurementId: 'G-2LD9N7WJK1',
  );
}
